name: CI

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build ranna server
        run: go build -v ./cmd/ranna/main.go

      - name: Build example client
        run: go build -v ./examples/client/main.go

      - name: Run tests
        run: go test -v ./...

